//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int RoomID { get; set; }
        public int UserID { get; set; }
        public System.DateTime C_Time { get; set; }
        public string Content { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}
